# Generated by Django 5.2.1 on 2025-05-18 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=30, verbose_name="Nickname")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "native_language",
                    models.CharField(
                        choices=[
                            ("ko", "Korean"),
                            ("en", "English"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                        ],
                        max_length=2,
                        verbose_name="Native Language",
                    ),
                ),
                (
                    "born_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Born Year"
                    ),
                ),
                (
                    "show_born_year",
                    models.BooleanField(default=False, verbose_name="Show Born Year"),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nationality"
                    ),
                ),
                (
                    "show_nationality",
                    models.BooleanField(default=False, verbose_name="Show Nationality"),
                ),
                (
                    "major",
                    models.CharField(blank=True, max_length=100, verbose_name="Major"),
                ),
                (
                    "show_major",
                    models.BooleanField(default=False, verbose_name="Show Major"),
                ),
                (
                    "instagram_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Instagram ID"
                    ),
                ),
                (
                    "show_instagram",
                    models.BooleanField(
                        default=False, verbose_name="Show Instagram ID"
                    ),
                ),
                (
                    "personality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INTJ", "INTJ"),
                            ("INTP", "INTP"),
                            ("ENTJ", "ENTJ"),
                            ("ENTP", "ENTP"),
                            ("INFJ", "INFJ"),
                            ("INFP", "INFP"),
                            ("ENFJ", "ENFJ"),
                            ("ENFP", "ENFP"),
                            ("ISTJ", "ISTJ"),
                            ("ISFJ", "ISFJ"),
                            ("ESTJ", "ESTJ"),
                            ("ESFJ", "ESFJ"),
                            ("ISTP", "ISTP"),
                            ("ISFP", "ISFP"),
                            ("ESTP", "ESTP"),
                            ("ESFP", "ESFP"),
                        ],
                        max_length=4,
                        verbose_name="Personality",
                    ),
                ),
                (
                    "show_personality",
                    models.BooleanField(default=False, verbose_name="Show Personality"),
                ),
                (
                    "purpose",
                    models.JSONField(blank=True, default=list, verbose_name="Purpose"),
                ),
                (
                    "show_purpose",
                    models.BooleanField(default=False, verbose_name="Show Purpose"),
                ),
                (
                    "bio",
                    models.CharField(blank=True, max_length=200, verbose_name="Bio"),
                ),
                (
                    "show_bio",
                    models.BooleanField(default=False, verbose_name="Show Bio"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
