# Generated by Django 5.2.1 on 2025-05-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_visit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hobbies", "Hobbies & Leisure"),
                            ("Travel", "Travel & Adventure"),
                            ("Food", "Food & Drink"),
                            ("Music", "Music"),
                            ("Sports", "Sports"),
                            ("Entertainment", "Entertainment & Media"),
                            ("Beauty", "Beauty & Fashion"),
                            ("Science", "Science & IT"),
                            ("Social", "Social & Community"),
                            ("Creative", "Creative & Arts"),
                            ("Pets", "Pets & Animals"),
                            ("Language", "Languages"),
                            ("Auto", "Automotive & Motorsports"),
                            ("Culture", "Arts & Culture"),
                        ],
                        max_length=20,
                        verbose_name="Interest Category",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Interest Name"),
                ),
            ],
            options={
                "verbose_name": "Interest",
                "verbose_name_plural": "Interests",
            },
        ),
        migrations.DeleteModel(
            name="Visit",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                to="accounts.interest",
                verbose_name="User-selected Interests",
            ),
        ),
    ]
