# Generated by Django 5.2.1 on 2025-05-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_topic_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorite_categories",
            field=models.ManyToManyField(
                blank=True, to="accounts.category", verbose_name="관심 카테고리"
            ),
        ),
    ]
